### ISSUE TITLE
Relative paths to image files

### ISSUE THREAD

**Issue by infinitymdm** [Icosahunter/dross#1]
When I first compiled the game, I tried to run it from the build directory. It spit out the following errors:
```
Failed to load image "./images/face.png". Reason: Unable to open file
Failed to load image "./images/red.png". Reason: Unable to open file
Failed to load image "./images/Death_sphere.png". Reason: Unable to open file
Failed to load image "./images/face_2.png". Reason: Unable to open file
Failed to load image "./images/boss.png". Reason: Unable to open file
Failed to load image "./images/boss2.png". Reason: Unable to open file
Failed to load image "./images/wall.png". Reason: Unable to open file
Failed to load image "./images/enemyMissile.png". Reason: Unable to open file
Failed to load font "./fonts/RubikBurned/RubikBurned-Regular.ttf" (failed to create the font face)
Failed to load image "./images/back.png". Reason: Unable to open file
Unable to load stars texture!
```
This implies that these images are not actually compiled into the binary, but instead rely on relative paths. I think this can be fixed by modifying the build script, but I'm not 100% sure there.

Works fine when run from the same directory as I cloned it :+1: (except the numbers thing, which I understand you already know about)

**Comment by Icosahunter** [comment]
I'm aware of the relative image paths, when I make an installer everything will go in the correct place and you won't have to worry about it. For now you just have to move the executable prior to running (this is described in the build instructions).

**Comment by Icosahunter** [comment]
Never mind, I see what you're saying, having them as relative to working directory isn't what we want. I will add setting the data directory as a build option.

**Comment by Icosahunter** [comment]
Ok, build options are added. The situation will be further improved when I add the ability for installation.
